name: All Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-all:
    name: Run Tests and Linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      # https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/
      - name: Cache Npm
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci
      
      - name: Install Client Node.js dependencies
        working-directory: './client'
        run: npm ci
      
      - name: Install Server Node.js dependencies
        working-directory: './server'
        run: npm ci
      
      - name: Run lint for overall
        run: npm run lint
      
      - name: Run frontend tests
        working-directory: './client'
        run: npm run test

      - name: Run backend unit tests
        working-directory: './server'
        run: npm run test-unit
